# @package _global_

stage_1:
  target: ocr-noise

misc:
  latent_size: [1280, 8, 8] # [C, H, W]
training:
  sample_every: 2500
  gen_global_batch_size: 16

stage_2:
  params:
    input_size: 8
    in_channels: 1280    
    y_embedder: false